#!/bin/bash
# MoAI PostToolUseFailure Hook Wrapper - Generated by moai-adk
# This script forwards stdin JSON to the moai hook post-tool-failure command.
# Project-local hook: .claude/hooks/moai/handle-post-tool-failure.sh

# Create temp file to store stdin
temp_file=$(mktemp)
trap 'rm -f "$temp_file"' EXIT

# Read stdin into temp file
cat > "$temp_file"

# Try moai command in PATH
if command -v moai &> /dev/null; then
	exec moai hook post-tool-failure < "$temp_file" 2>/dev/null
fi

# Try detected Go bin path from initialization
if [ -f "/home/szw001/go/bin/moai" ]; then
	exec "/home/szw001/go/bin/moai" hook post-tool-failure < "$temp_file" 2>/dev/null
fi

# Try default ~/go/bin/moai
if [ -f "$HOME/go/bin/moai" ]; then
	exec "$HOME/go/bin/moai" hook post-tool-failure < "$temp_file" 2>/dev/null
fi

# Try ~/.local/bin/moai (Linux install location)
if [ -f "$HOME/.local/bin/moai" ]; then
	exec "$HOME/.local/bin/moai" hook post-tool-failure < "$temp_file" 2>/dev/null
fi

# Not found - exit silently (Claude Code handles missing hooks gracefully)
exit 0
